name: Xiaoming(Leo) Wang
avatar: https://cdn.jsdelivr.net/gh/dawnseeker8/img-hosting/images/photo.jpg # Avatar image. Default to "images/profile.webp".
bio: "Gopher, Javaer, Rust, ReactJS, Full Stack Engineer."
# company: Company # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: UK && China # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {}
# layout: compact
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  email: dawnseeker8@gmail.com
  github: dawnseeker8
  twitter: dawnseeker8
  paypal: dawnseeker8
  rss: "" # Remove RSS
