baseURL: /
title: Xiaoming(Leo) Wang's Personal blogs
theme: hugo-theme-bootstrap
copyright: "Copyright © 2016-{year} By Xiaoming(Leo) Wang"
defaultContentLanguage: zh-cn
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
paginate: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45
# disqusShortname: yourdiscussshortname

blackfriday:
  hrefTargetBlank: false

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: false

permalinks:
  news: /news/:year/:month/:title/
# module:
# proxy: https://goproxy.cn
