# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
email: dawnseeker8@gmail.com
facebook: dawnseeker8
github: dawnseeker8
gitlab: dawnseeker8
linkedin: xiaoming-wang-9871672
# xing: yourxingusername
stackoverflow: dawnseeker8
# twitter: dawnseeker8
# weibo: yourweibousername
# zhihu: yourzhihuusername
# instagram: yourinstagramusername
# quora: yourquorausername
# tumblr: yourtumblrusername
# reddit: yourredditusername
# telegram: yourtelegramusername
qq: 377189809
# dockerhub: yourdockerhubusername
# bitbucket: dawnseeker8
# kaggle: yourkaggleusername
# medium: yourmediumusername # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm: yourlastfmusername
bilibili: 1159059660
youtube: dawnseeker8
# discord: yourdiscordinvitecode
# discourse: https://yourforum.tld
# facebookgroup: yourfacebookgroupname
tiktok: yourtiktokusername
# pinterest: yourpinterestusername
# mastodon: yourmastodonusername
# liberapay: yourliberapayaccount
paypal: dawnseeker8
# patreon: razonyang
# tipeee: yourtipeeeaccount-fr
